import http from 'node:http';
import { getAdminFirestore } from './src/firebase-admin.mjs';
import { createFirestoreStore } from './src/firestore.mjs';
import { cadastrarMotoristaNoLayan, cadastrarVeiculoNoLayan } from './src/layan-driver.mjs';
import { processInput } from './src/core.mjs';
import { classifyWithKie } from './src/luna.mjs';

const port = Number(process.env.PORT || 10000);
const origin = process.env.CORS_ORIGIN || 'https://cadastromotora.pages.dev';
const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': origin, 'access-control-allow-headers': 'content-type', 'access-control-allow-methods': 'GET,POST,OPTIONS' }); res.end(JSON.stringify(body)); };
const readBody = req => new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 1e6) reject(new Error('payload muito grande')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch (e) { reject(e); } }); req.on('error', reject); });
const run = async (id, payload, store) => { const etapas = [{ etapa: 'firestore', status: 'concluida', mensagem: 'Gravando no Firestore' }]; const motorista = await cadastrarMotoristaNoLayan(payload.motorista, { timeoutMs: 20000 }); etapas.push({ etapa: 'motorista', status: motorista.sucesso ? 'concluida' : 'falhou', resultado: motorista }); if (!motorista.sucesso) { await store.set(id, { status: 'falha_motorista', etapas, atualizadoEm: new Date().toISOString() }); return { ok: false, cadastroId: id, etapas }; } const veiculo = await cadastrarVeiculoNoLayan({ ...payload.veiculo, proprietarioNome: payload.motorista.nome, motoristaNome: payload.motorista.nome }, { timeoutMs: 20000 }); etapas.push({ etapa: 'veiculo', status: veiculo.sucesso ? 'concluida' : 'falhou', resultado: veiculo }); const status = veiculo.sucesso ? 'concluido' : 'falha_veiculo'; await store.set(id, { status, layanMotoristaId: motorista.layanMotoristaId, layanVeiculoId: veiculo.layanVeiculoId ?? null, etapas, atualizadoEm: new Date().toISOString() }); return { ok: veiculo.sucesso, cadastroId: id, etapas }; };
const evolutionText = event => event?.data?.message?.conversation ?? event?.data?.message?.extendedTextMessage?.text ?? event?.message?.conversation ?? event?.message?.extendedTextMessage?.text ?? event?.data?.body ?? null;
const evolutionSender = event => event?.data?.key?.remoteJid?.split('@')[0] ?? event?.data?.key?.participant?.split('@')[0] ?? event?.key?.remoteJid?.split('@')[0] ?? event?.sender ?? null;
const evolutionInstance = event => event?.instance ?? event?.data?.instance ?? event?.data?.instanceName ?? null;
async function downloadEvolutionMedia(event) {
  const instance = evolutionInstance(event); const key = process.env.EVOLUTION_API_KEY; const base = (process.env.EVOLUTION_API_URL || '').replace(/\/$/, '');
  if (!instance || !key || !base) throw new Error('EVOLUTION_API_URL/EVOLUTION_API_KEY não configurados para mídia');
  const message = event?.data?.message ?? event?.message; const response = await fetch(`${base}/chat/getBase64FromMediaMessage/${encodeURIComponent(instance)}`, { method: 'POST', headers: { apikey: key, 'content-type': 'application/json' }, body: JSON.stringify({ message: { key: event?.data?.key ?? event?.key, message } }) });
  if (!response.ok) throw new Error(`Evolution mídia HTTP ${response.status}`); const body = await response.json(); const base64 = body.base64 ?? body.data?.base64; if (!base64) throw new Error('Evolution não retornou base64 da mídia');
  return base64.startsWith('data:') ? base64 : `data:${message?.imageMessage ? 'image/jpeg' : 'application/octet-stream'};base64,${base64}`;
}
async function handleEvolution(event, store) {
  const sender = evolutionSender(event); if (!sender) throw new Error('remetente ausente no evento Evolution');
  const cadastroId = `whatsapp:${sender}`; const text = evolutionText(event); const message = event?.data?.message ?? event?.message ?? {};
  const image = message.imageMessage || message.documentMessage || event?.data?.base64 || event?.base64;
  const input = text ? { kind: 'text', value: text, source: 'evolution:MESSAGES_UPSERT' } : image ? { kind: 'image', value: event?.data?.base64 || event?.base64 || await downloadEvolutionMedia(event), source: 'evolution:MESSAGES_UPSERT' } : null;
  if (!input) { await store.append(cadastroId, 'historicoBruto', { recebidoEm: new Date().toISOString(), tipo: 'unknown', valor: event, origem: 'evolution:MESSAGES_UPSERT', motivo: 'mensagem sem texto ou mídia' }); return; }
  return processInput({ store, cadastroId, motoristaId: sender, input, classifier: classifyWithKie });
}
const server = http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return json(res, 204, {}); if (req.url === '/health' && req.method === 'GET') return json(res, 200, { ok: true, service: 'layanlog-render' }); try { const store = createFirestoreStore(getAdminFirestore()); const url = new URL(req.url, `http://${req.headers.host}`); if (req.method === 'GET' && url.pathname.startsWith('/status/')) { const doc = await store.get(url.pathname.split('/').pop()); return doc ? json(res, 200, doc) : json(res, 404, { ok: false, erro: 'Cadastro não encontrado' }); } if (req.method === 'POST' && url.pathname === '/webhook/evolution') { const payload = await readBody(req); if (payload.event && payload.event !== 'MESSAGES_UPSERT') return json(res, 202, { ok: true, ignorado: payload.event }); json(res, 202, { ok: true, recebido: true }); void handleEvolution(payload, store).catch(error => console.error('[evolution-webhook]', error)); return; } if (req.method !== 'POST' || url.pathname !== '/cadastrar-motorista-veiculo') return json(res, 404, { ok: false, erro: 'Rota não encontrada' }); const payload = await readBody(req); if (payload.modoMock) return json(res, 200, { ok: true, modoMock: true, etapas: [{ etapa: 'concluido', status: 'concluida', mensagem: 'Simulação concluída' }] }); const id = `render-${Date.now()}`; await store.set(id, { id, payload, status: 'processando', criadoEm: new Date().toISOString() }); const result = await run(id, payload, store); return json(res, result.ok ? 200 : 422, result); } catch (error) { return json(res, 500, { ok: false, erro: error.message }); } });
server.listen(port, '0.0.0.0', () => console.log(`layanlog-render listening on ${port}`));
