import http from 'node:http';
import { getAdminFirestore } from './src/firebase-admin.mjs';
import { createFirestoreStore } from './src/firestore.mjs';
import { cadastrarMotoristaNoLayan, cadastrarVeiculoNoLayan } from './src/layan-driver.mjs';

const port = Number(process.env.PORT || 10000);
const origin = process.env.CORS_ORIGIN || 'https://cadastromotora.pages.dev';
const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': origin, 'access-control-allow-headers': 'content-type', 'access-control-allow-methods': 'GET,POST,OPTIONS' }); res.end(JSON.stringify(body)); };
const readBody = req => new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 1e6) reject(new Error('payload muito grande')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch (e) { reject(e); } }); req.on('error', reject); });
const run = async (id, payload, store) => { const etapas = [{ etapa: 'firestore', status: 'concluida', mensagem: 'Gravando no Firestore' }]; const motorista = await cadastrarMotoristaNoLayan(payload.motorista, { timeoutMs: 20000 }); etapas.push({ etapa: 'motorista', status: motorista.sucesso ? 'concluida' : 'falhou', resultado: motorista }); if (!motorista.sucesso) { await store.set(id, { status: 'falha_motorista', etapas, atualizadoEm: new Date().toISOString() }); return { ok: false, cadastroId: id, etapas }; } const veiculo = await cadastrarVeiculoNoLayan({ ...payload.veiculo, proprietarioNome: payload.motorista.nome, motoristaNome: payload.motorista.nome }, { timeoutMs: 20000 }); etapas.push({ etapa: 'veiculo', status: veiculo.sucesso ? 'concluida' : 'falhou', resultado: veiculo }); const status = veiculo.sucesso ? 'concluido' : 'falha_veiculo'; await store.set(id, { status, layanMotoristaId: motorista.layanMotoristaId, layanVeiculoId: veiculo.layanVeiculoId ?? null, etapas, atualizadoEm: new Date().toISOString() }); return { ok: veiculo.sucesso, cadastroId: id, etapas }; };
const server = http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return json(res, 204, {}); if (req.url === '/health' && req.method === 'GET') return json(res, 200, { ok: true, service: 'layanlog-render' }); try { const store = createFirestoreStore(getAdminFirestore()); const url = new URL(req.url, `http://${req.headers.host}`); if (req.method === 'GET' && url.pathname.startsWith('/status/')) { const doc = await store.get(url.pathname.split('/').pop()); return doc ? json(res, 200, doc) : json(res, 404, { ok: false, erro: 'Cadastro não encontrado' }); } if (req.method !== 'POST' || url.pathname !== '/cadastrar-motorista-veiculo') return json(res, 404, { ok: false, erro: 'Rota não encontrada' }); const payload = await readBody(req); if (payload.modoMock) return json(res, 200, { ok: true, modoMock: true, etapas: [{ etapa: 'concluido', status: 'concluida', mensagem: 'Simulação concluída' }] }); const id = `render-${Date.now()}`; await store.set(id, { id, payload, status: 'processando', criadoEm: new Date().toISOString() }); const result = await run(id, payload, store); return json(res, result.ok ? 200 : 422, result); } catch (error) { return json(res, 500, { ok: false, erro: error.message }); } });
server.listen(port, '0.0.0.0', () => console.log(`layanlog-render listening on ${port}`));
